"""Add background_tasks table for async operation tracking

Revision ID: d85347b4bc45
Revises: b7d2e8a4f9c6
Create Date: 2025-09-02 11:50:43.806742

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd85347b4bc45'
down_revision = 'b7d2e8a4f9c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create background_tasks table
    op.create_table('background_tasks',
        sa.Column('id', sa.CHAR(length=36), nullable=False),
        sa.Column('user_id', sa.CHAR(length=36), nullable=False),
        sa.Column('task_type', sa.String(length=50), nullable=False),
        sa.Column('task_name', sa.String(length=100), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('progress_percentage', sa.Float(), nullable=True),
        sa.Column('progress_message', sa.String(length=255), nullable=True),
        sa.Column('result_data', sa.JSON(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.Index('ix_background_tasks_id', 'id'),
        sa.Index('ix_background_tasks_user_id', 'user_id'),
        sa.Index('ix_background_tasks_status', 'status'),
        sa.Index('ix_background_tasks_task_type', 'task_type'),
        sa.Index('ix_background_tasks_created_at', 'created_at'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop background_tasks table
    op.drop_table('background_tasks')
    # ### end Alembic commands ###